Feature/lefthook
Gold-Labs/typescript-bolierplate pull request #4
Opened 2023-12-30 07:44 UTC by player31-kks

### 주요 변경 사항
* lefthook 적용
* commitlint 적용

2023-12-30 07:47 UTC, youngkyo0504 requested changes

2023-12-30 07:47 UTC, youngkyo0504 commented on lefthook.yml
> +# EXAMPLE USAGE:
안쓰는 코드는 지우는 것은 어떤가요?

2023-12-31 01:06 UTC, player31-kks commented on lefthook.yml
> +# EXAMPLE USAGE:
넵 수정했습니다!

2023-12-31 02:26 UTC, youngkyo0504 approved these changes

2023-12-31 02:26 UTC, merged